export const allowedFileTaskDirs = [
	"mise-tasks",
	".mise-tasks",
	"mise/tasks",
	".mise/tasks",
	".config/mise/tasks",
];

export const misePatterns = [
	".config/mise/config.toml",
	"mise/config.toml",
	"mise.toml",
	".mise/config.toml",
	".mise.toml",
	".config/mise/config.local.toml",
	"mise/config.local.toml",
	"mise.local.toml",
	".mise/config.local.toml",
	".mise.local.toml",
	".config/mise/config.*.toml",
	"mise/config.*.toml",
	"mise.*.toml",
	".mise/config.*.toml",
	".mise.*.toml",
	".config/mise/config.*.local.toml",
	"mise/config.*.local.toml",
	".mise/config.*.local.toml",
	".mise.*.local.toml",
].join(",");

export const legacyFiles = new Set([
	".crystal-version",
	".exenv-version",
	".go-version",
	"go.mod",
	".java-version",
	".sdkmanrc",
	".nvmrc",
	".node-version",
	".python-version",
	".ruby-version",
	"Gemfile",
	".terraform-version",
	".packer-version",
	"main.tf",
	".yarnrc",
]);
