name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MISE_LOCKED: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151  # v4.0.1
        with:
          install: true
          cache: true

      - run: aube ci --frozen-lockfile
      - run: node --run lint
      - run: node --run ts-check
      - run: node --run test
      - run: node --run build

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151  # v4.0.1
        with:
          install: true
          cache: true

      - run: sudo apt update
      - uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05  # v1.6.0
        with:
          packages: 'libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libgtk-3-0 libx11-xcb1 libxcb-dri3-0 libxss1 xvfb dbus-x11'
          version: 1.0

      - run: aube ci --frozen-lockfile
      - run: node --run build
      - run: xvfb-run -a node --run e2e-tests
